//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPB.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public string EmployeeAcenumber { get; set; }
        public int SpaceId { get; set; }
        public string VehicalRegistrationNumber { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public Nullable<int> TotalHours { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ParkingSpace ParkingSpace { get; set; }
    }
}
